name: Feishu Notification

on:
  push:

jobs:
  growth:
    runs-on: ubuntu-latest
    env:
      FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.4.0
          cache: 'npm'
      - name: Depend install
        run: npm ci
      - name: run serve
        run: npm run serve
