name: Growth

on:
  push:

jobs:
  growth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.4.0
          cache: 'npm'
      - name: Depend install
        run: npm ci
      - name: run serve
        env:
          FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
        run: npm run serve
